default: &default
  adapter: postgresql
  encoding: unicode
  username: mini_blog2
  password: <%= Rails.application.credentials.db[:password] %>
  host: localhost
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mini_blog2_development

test:
  <<: *default
  database: mini_blog2_test

production:
  <<: *default
  database: mini_blog2_production
